# Run build-ns3
name: build-ns3

on: [push, pull_request]

jobs:
  build-on-ns3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ns3 build
      uses: marshallasch/ns3-action@V0.9.0
      with:
        location: 'scratch'
        #pre_run: 'pre.sh'
        sim_name: 'speedfalloff-plots'
        sim_args: '--runTime=10'
